const actionTypes = {
	FILMS_REQUEST: 'FILMS_REQUEST',
	FILMS_REQUEST_SUCCESS: 'FILMS_REQUEST_SUCCESS',
	FILMS_REQUEST_SUCCESS_FAILED: 'FILMS_REQUEST_SUCCESS_FAILED',

	PEOPLE_REQUEST: 'PEOPLE_REQUEST',
	PEOPLE_REQUEST_SUCCESS: 'PEOPLE_REQUEST_SUCCESS',
	PEOPLE_REQUEST_SUCCESS_FAILED: 'PEOPLE_REQUEST_SUCCESS_FAILED',

	SPECIES_REQUEST: 'SPECIES_REQUEST',
	SPECIES_REQUEST_SUCCESS: 'SPECIES_REQUEST_SUCCESS',
	SPECIES_REQUEST_SUCCESS_FAILED: 'SPECIES_REQUEST_SUCCESS_FAILED',

	STARSHIPS_REQUEST: 'STARSHIPS_REQUEST',
	STARSHIPS_REQUEST_SUCCESS: 'STARSHIPS_REQUEST_SUCCESS',
	STARSHIPS_REQUEST_SUCCESS_FAILED: 'STARSHIPS_REQUEST_SUCCESS_FAILED',

	VEHICLES_REQUEST: 'VEHICLES_REQUEST',
	VEHICLES_REQUEST_SUCCESS: 'VEHICLES_REQUEST_SUCCESS',
	VEHICLES_REQUEST_SUCCESS_FAILED: 'VEHICLES_REQUEST_SUCCESS_FAILED',
};

export default actionTypes;
